// apps/frontend-v2/src/components/system/SystemSummary.tsx
import { Title } from '../ui/typography/Title';
import { Subtitle } from '../ui/typography/Subtitle';
import { Sanitized } from '../Sanitized';
import { string } from '@/app/system/field/utils';
import { SystemDtoInterface } from '@app/v2/dto/system/SystemDtoInterface';
import { ColorCircle } from '../ui/elements/ColorCircle';
import { Tag } from '../ui/elements/Tag';
import { Visibility } from '@prisma/client';
import { useSystemMutation } from '@/hooks/system/mutation';
import { DocumentIcon } from '@heroicons/react/24/outline';
import { useState } from 'react';
import Link from 'next/link';
import { Editor } from '../ui/form/Editor';
import { ButtonLink } from '../ui/elements/Button';
import { UserContent } from '../ui/elements/UserContent';

export interface SystemSummaryProps {
  system: SystemDtoInterface;
  dashboardMode?: boolean;
}

export const SystemSummary = ({ system, dashboardMode = false }: SystemSummaryProps) => {
  const mutation = useSystemMutation();

  const [disabled, setDisabled] = useState(false);

  const toggleVisibility = async () => {
    setDisabled(true);

    try {
      await mutation.mutateAsync({
        visibility: system.data.visibility === Visibility.Public ? Visibility.Private : Visibility.Public,
      });
    } catch (e) {
      console.error('Failed to toggle visibility for system', { system, e });
    }

    setDisabled(false);
  };

  return (
    <>
      <div className="flex justify-between items-start">
        <div className="mb-5 flex flex-col text-center sm:flex-row sm:text-left justify-left items-center gap-4">
          {system.avatar ? (
            <img src={system.avatar} alt={system.name} className="flex-shrink-0 w-32 h-32 rounded-full object-cover" />
          ) : (
            <ColorCircle color={system.color} className="flex-shrink-0 !w-32 !h-32 opacity-25" />
          )}

          <div>
            {dashboardMode && <p className="text-sm text-gray-700">ID: {system.id}</p>}

            <Title className="inline-flex flex-col sm:flex-row items-center justify-center gap-3">
              {system.name}

              {dashboardMode && (
                <>
                  <Tag
                    toggled={system.data.visibility === Visibility.Public}
                    disabled={disabled}
                    onToggle={toggleVisibility}
                  >
                    {system.data.visibility}
                  </Tag>

                  {system.data.visibility === Visibility.Public && (
                    <Link
                      href={`/${system.data.slug}`}
                      className="text-sm text-gray-700 font-normal"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <u>Open public view</u>
                    </Link>
                  )}
                </>
              )}
            </Title>

            {system.description && (
              <Subtitle className="mb-3">
                <Sanitized unsafeValue={string(system.description, true)} />
              </Subtitle>
            )}

            {system.color && (
              <span className="inline-flex text-gray-700 items-center gap-1">
                Color: {system.color} <ColorCircle color={system.color} />
              </span>
            )}
          </div>
        </div>

        {dashboardMode && (
          <div className="flex items-center gap-2">
            <ButtonLink
              href={'/dashboard/system/page/add'}
              className="border-[2.5px] bg-white bg-opacity-25 border-violet-300 text-black inline-flex justify-center items-center gap-1"
            >
              <DocumentIcon className="w-8 h-8 -ml-1" />
              <span>New Page</span>
            </ButtonLink>
          </div>
        )}
      </div>

      {dashboardMode ? (
        <Editor
          initialValue={system.data.description ?? ''}
          placeholder={`Add custom description for ${system.name}...`}
        />
      ) : (
        system.data.description && (
          <UserContent>
            <Sanitized unsafeValue={system.data.description} />
          </UserContent>
        )
      )}
    </>
  );
};

// apps/frontend/src/components/global/system/SystemSummary.vue
<template>
  <div class="flex justify-between items-start">
    <div class="mb-5 flex flex-col text-center sm:flex-row sm:text-left justify-left items-center gap-4">
      <img
        v-if="system.avatar"
        :src="system.avatar"
        :alt="system.username"
        class="flex-shrink-0 w-32 h-32 rounded-full object-cover"
      />
      <Color v-else :color="system.color ?? '#e2e8f0'" class="flex-shrink-0 !w-32 !h-32 opacity-25" />
      <div>
        <p class="text-sm text-gray-700" v-if="isDashboard">SID: {{ system.id }}</p>
        <PageTitle class="inline-flex flex-col sm:flex-row items-center justify-center gap-3">
          {{ system.username }}
          <VisibilityTag
            v-if="isDashboard"
            :disabled="loading"
            :visible="system.data.visible"
            @click.prevent="toggleVisibility"
          />
          <a
            v-if="isDashboard && system.data.visible"
            :href="`/${system.data.slug}`"
            class="text-sm text-gray-700 font-normal"
            target="_blank"
            rel="noopener noreferrer"
          >
            <u>Open public view</u>
          </a>
        </PageTitle>
        <Subtitle class="mb-3" v-if="system.description">
          <Sanitized :value="string(system.description, true)"/>
        </Subtitle>
        <span v-if="system.color" class="inline-flex text-gray-700 items-center gap-1">
          Color: {{ system.color }}
          <ColorCircle :color="system.color" />
        </span>
      </div>
    </div>

    <div v-if="isDashboard" class="flex items-center gap-2">
      <BackgroundChooser v-model:entity="system" type="system" />
      <ButtonLink
        :to="{ name: 'dashboard:system:page:create', params: $route.params }"
        class="border-[2.5px] bg-white bg-opacity-25 border-violet-300 text-black inline-flex justify-center items-center gap-1"
      >
        <DocumentIcon class="w-8 h-8 -ml-1" />
        <span>New Page</span>
      </ButtonLink>
    </div>
  </div>

  <Editor
    v-if="isDashboard"
    :id="`${system.id}_customDescription`"
    :initial-value="system.data.customDescription"
    :placeholder="`Add custom description for ${system.username}...`"
    @save="updateCustomDescription"
  />
  <UserContent class="mb-5 p-6" v-else-if="system.data.customDescription">
    <Sanitized :value="system.data.customDescription" />
  </UserContent>

  <CustomFields :fields="system.fields" :modifiable="isDashboard" />
</template>
<script lang="ts">
import PageTitle from '../../Title.vue';
import Color from '../color/ColorCircle.vue';
import Subtitle from '../../Subtitle.vue';
import ColorCircle from '../color/ColorCircle.vue';
import { computed, defineComponent, PropType, ref } from 'vue';
import type { SystemDto } from '@app/v1/dto/user/system/SystemDto';
import { useRoute } from 'vue-router';
import VisibilityTag from '../visibility/VisibilityTag.vue';
import { wrapRequest } from '../../../api';
import { updateSystem } from '../../../api/system';
import { Editor as EditorType } from 'tinymce';
import CustomFields from '../fields/CustomFields.vue';
import UserContent from '../UserContent.vue';
import Sanitized from '../Sanitized.vue';
import Editor from '../../dashboard/Editor.vue';
import BackgroundChooser from '../BackgroundChooser.vue';
import Fetchable from '../Fetchable.vue';
import ButtonLink from '../../ButtonLink.vue';
import { DocumentIcon } from '@heroicons/vue/24/outline';
import { string } from '../../../api/fields';

export default defineComponent({
  components: {
    VisibilityTag,
    PageTitle,
    Color,
    Subtitle,
    ColorCircle,
    CustomFields,
    Editor,
    UserContent,
    Sanitized,
    BackgroundChooser,
    Fetchable,
    ButtonLink,
    DocumentIcon
},
  props: {
    entity: {
      type: Object as PropType<SystemDto>,
      required: true,
    },
  },
  emits: ['update:entity'],
  setup(props, { emit }) {
    const route = useRoute();

    const loading = ref(false);

    const system = computed({
      get() {
        return props.entity;
      },
      set(v) {
        emit('update:entity', v);
      },
    });

    const toggleVisibility = async () => {
      if (loading.value) return;
      loading.value = true;

      const res = await wrapRequest(() =>
        updateSystem({
          visible: !system.value.data.visible,
        })
      );

      // fail??? refresh
      if (!res) return (window.location.href = '');

      system.value = res.system;
      loading.value = false;
    };

    const updateCustomDescription = async (editor: EditorType) => {
      if (loading.value) return;
      loading.value = true;

      const res = await wrapRequest(() => {
        if (!system.value) return null;

        editor.readonly = true;
        let customDescription: string | null = editor.getContent({ format: 'html' });

        if (editor.getContent({ format: 'text' }).trim().length < 1) {
          customDescription = null;
        }

        return updateSystem({
          customDescription,
        });
      });

      if (res) {
        system.value = res.system;
      }

      loading.value = false;
    };

    return {
      toggleVisibility,
      updateCustomDescription,
      loading,
      system,
      string,
      isDashboard: computed(() => route.path.startsWith('/dashboard')),
    };
  },
});
</script>
