// apps/frontend/src/components/global/Sanitized.vue
<template>
  <div ref="div" />
</template>

<script lang="ts">
import { Sanitizer, setHTML } from "@plurali/sanitizer";
import { defineComponent, onMounted, ref } from "vue";

export default defineComponent({
  props: {
    value: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const s = ref<Sanitizer>(new Sanitizer());
    const div = ref<HTMLDivElement>();

    onMounted(() => {
      if (div.value) {
        setHTML.bind(div.value)(props.value, { sanitizer: s.value });
      }
    });

    return {
      s,
      div,
    };
  },
});
</script>

// apps/frontend-v2/src/components/Sanitized.tsx
import { Sanitizer, setHTML } from '@plurali/sanitizer';
import { hasWindow } from '@/app/utils';
import { useState, useEffect } from 'react';

export interface SanitizedProps {
  unsafeValue: string;
}

export const Sanitized = ({ unsafeValue }: SanitizedProps) => {
  const [ref, setRef] = useState<HTMLDivElement | null>(null);

  useEffect(() => {
    if (hasWindow() && ref) {
      const sanitizer = new Sanitizer();
      setHTML.bind(ref)(unsafeValue, { sanitizer });
    }
  }, [ref, unsafeValue]);

  return <div ref={setRef}></div>;
};
