// frontend-v2/src/components/ui/elements/ColorCircle.tsx
import { c } from "@/app/utils"

export interface ColorCircleProps {
  className?: string,
  color?: string | null
}

const DefaultColor = "#e2e8f0";

export const ColorCircle = ({ className, color = DefaultColor }: ColorCircleProps) => <div
  style={{ backgroundColor: color ?? DefaultColor }}
  className={c("w-6 h-6 rounded-full border border-gray-400", className)}
></div>

// apps/frontend/src/components/global/color/ColorCircle.vue
<template>
  <div :style="{ backgroundColor: color }" class="w-6 h-6 rounded-full border border-gray-400" />
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    color: {
      type: String,
      default: "#fff",
    },
  },
});
</script>
