// frontend-v2/src/components/ui/elements/Modal.tsx
import { Dialog, } from "@headlessui/react"
import { ModelProps } from "@/components/types/utils"
import { Fragment, PropsWithChildren, ReactNode, useMemo } from "react"
import { Transition } from "@headlessui/react"
import { Spinner } from "./Spinner"
import { c } from "@/app/utils"
import { XMarkIcon } from "@heroicons/react/24/outline"
import { Button } from "./Button"

export interface ModalProps extends PropsWithChildren<ModelProps<boolean>> {
    title: string,
    goBack?: string | null,
    loading?: boolean,
    color?: 'warning' | 'error' | 'success' | 'info' | string | null,
    renderIcon?: () => ReactNode
    renderHeader?: () => ReactNode
}

export const Modal = ({
    title,
    value,
    setValue,
    loading = false,
    goBack,
    color,
    renderIcon,
    renderHeader,
    children
}: ModalProps) => {
    const iconContainerColorClass = useMemo(() => color ? {
        warning: 'bg-orange-100',
        error: 'bg-red-100',
        success: 'bg-green-100',
        info: 'bg-blue-100',
    }[color] ?? null : null, [color]);

    const iconColorClass = useMemo(() => color ? {
        warning: 'text-orange-600',
        error: 'text-red-600',
        success: 'text-green-600',
        info: 'text-blue-600',
    }[color] ?? null : null, [color]);
    return (
        <Transition.Root as={Fragment} show={value}>
            <Dialog as="div" className="relative z-10" onClose={() => !loading && setValue(false)}>
                <Transition.Child
                    as={Fragment}
                    enter="ease-out duration-300"
                    enterFrom="opacity-0"
                    enterTo="opacity-100"
                    leave="ease-in duration-200"
                    leaveFrom="opacity-100"
                    leaveTo="opacity-0"
                >
                    <div className="fixed inset-0 bg-white bg-opacity-25 backdrop-blur-sm transition-opacity" />
                </Transition.Child>

                <div className="fixed inset-0 z-10 overflow-y-auto">
                    <div className="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                        <Transition.Child
                            as={Fragment}
                            enter="ease-out duration-300"
                            enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                            enterTo="opacity-100 translate-y-0 sm:scale-100"
                            leave="ease-in duration-200"
                            leaveFrom="opacity-100 translate-y-0 sm:scale-100"
                            leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                        >
                            <Dialog.Panel
                                className="relative transform overflow-hidden rounded-2xl bg-white p-8 text-left shadow-2xl transition-all sm:my-8 sm:max-w-sm lg:max-w-7xl !w-full"
                            >
                                {loading &&
                                    <div className="absolute inset-0 w-full h-full bg-white bg-opacity-75 flex justify-center items-center cursor-default z-10">
                                        <Spinner className="!text-violet-700 !w-12 !h-12" />
                                    </div>}
                                <div className="border-b-2 mb-6 pb-6 flex justify-between items-center gap-3">
                                    <div className="inline-flex items-center justify-start gap-3">
                                        {iconContainerColorClass && (
                                            <div
                                                className={c("inline-flex h-16 w-16 items-center justify-center rounded-full", iconContainerColorClass)}
                                            >
                                                {iconColorClass && (
                                                    <XMarkIcon className={c("h-8 w-8", iconColorClass)} />
                                                )}
                                                {renderIcon?.()}
                                            </div>
                                        )}
                                        <Dialog.Title as="h2" className="font-semibold leading-6 text-2xl lg:text-3xl text-gray-900">
                                            {title}
                                        </Dialog.Title>
                                    </div>

                                    {renderHeader?.()}
                                </div>

                                <div>
                                    {children}
                                </div>

                                <div className="mt-2 sm:mt-3">
                                    <slot name="footer"></slot>
                                    {goBack && (
                                        <Button
                                            disabled={loading}
                                            type="button"
                                            className="inline-flex w-full justify-end bg-red-700 text-white font-semibold"
                                            onClick={() => !loading && setValue(false)}
                                        >
                                            {goBack}
                                        </Button>
                                    )}
                                </div>
                            </Dialog.Panel>
                        </Transition.Child>
                    </div>
                </div >
            </Dialog>
        </Transition.Root >
    )
}

// apps/frontend/src/components/global/Modal.vue
<template>
  <TransitionRoot as="template" :show="modelValue">
    <Dialog as="div" class="relative z-10" @close="() => (loading ? {} : $emit('update:modelValue', false))">
      <TransitionChild
        as="template"
        enter="ease-out duration-300"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="ease-in duration-200"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-white bg-opacity-25 backdrop-blur-sm transition-opacity" />
      </TransitionChild>

      <div class="fixed inset-0 z-10 overflow-y-auto">
        <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
          <TransitionChild
            as="template"
            enter="ease-out duration-300"
            enter-from="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            enter-to="opacity-100 translate-y-0 sm:scale-100"
            leave="ease-in duration-200"
            leave-from="opacity-100 translate-y-0 sm:scale-100"
            leave-to="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          >
            <DialogPanel
              class="relative transform overflow-hidden rounded-2xl bg-white p-8 text-left shadow-2xl transition-all sm:my-8 sm:max-w-sm lg:max-w-7xl !w-full"
            >
              <div
                v-if="loading"
                class="absolute inset-0 w-full h-full bg-white bg-opacity-75 flex justify-center items-center cursor-default z-10"
              >
                <Spinner class="!text-violet-700 !w-12 !h-12" />
              </div>
              <div class="border-b-2 mb-6 pb-6 flex justify-between items-center gap-3">
                <div class="inline-flex items-center justify-start gap-3">
                  <div
                    v-if="iconContainerClass"
                    class="inline-flex h-16 w-16 items-center justify-center rounded-full"
                    :class="iconContainerClass"
                  >
                    <XMarkIcon v-if="color === 'error'" class="h-8 w-8 text-red-600" aria-hidden="true" />
                    <XMarkIcon v-else-if="color === 'warning'" class="h-8 w-8 text-orange-600" aria-hidden="true" />
                    <XMarkIcon v-else-if="color === 'success'" class="h-8 w-8 text-green-600" aria-hidden="true" />
                    <XMarkIcon v-else-if="color === 'info'" class="h-8 w-8 text-blue-600" aria-hidden="true" />
                    <slot name="icon" />
                  </div>
                  <DialogTitle as="h2" class="font-semibold leading-6 text-2xl lg:text-3xl text-gray-900">
                    {{ title }}
                  </DialogTitle>
                </div>

                <slot name="header" />
              </div>

              <div>
                <slot />
              </div>

              <div class="mt-2 sm:mt-3">
                <slot name="footer" />
                <Button
                  v-if="goBack"
                  :disabled="loading"
                  type="button"
                  class="inline-flex w-full justify-end bg-red-700 text-white font-semibold"
                  @click="() => (loading ? {} : $emit('update:modelValue', false))"
                >
                  {{ goBack }}
                </Button>
              </div>
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script lang="ts">
import { Dialog, DialogPanel, DialogTitle, TransitionChild, TransitionRoot } from "@headlessui/vue";
import { XMarkIcon } from "@heroicons/vue/24/outline";
import { computed, defineComponent, PropType } from "vue";

import Button from "../Button.vue";
import Spinner from "../Spinner.vue";

export default defineComponent({
  components: {
    Dialog,
    TransitionRoot,
    TransitionChild,
    DialogPanel,
    DialogTitle,
    XMarkIcon,
    Button,
    Spinner,
  },
  props: {
    modelValue: {
      type: Boolean,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    color: {
      type: String as PropType<"warning" | "error" | "success" | "info" | string | null>,
      default: null,
    },
    goBack: {
      type: String,
      default: null,
    },
    loading: {
      type: Boolean,
      default: false,
    },
  },
  emits: ["update:modelValue"],
  setup(props) {
    const iconContainerClassMap = {
      warning: "bg-orange-100",
      error: "bg-red-100",
      success: "bg-green-100",
      info: "bg-blue-100",
    };

    const iconContainerClass = computed(() =>
      props.color ? (iconContainerClassMap[props.color as keyof typeof iconContainerClassMap] ?? props.color) : null,
    );

    return {
      iconContainerClass,
    };
  },
});
</script>
