// apps/frontend/src/pages/auth/register.vue
<template>
  <div class="mb-5">
    <Title>Register</Title>
    <Subtitle>Create a new Plurali account</Subtitle>
  </div>

  <form class="mb-4 w-full" @submit.prevent="submit">
    <div class="mb-3.5">
      <Label>Your username</Label>
      <input
        v-model="form.username"
        :disabled="loading"
        class="w-full p-2.5 border rounded-xl border-gray-400"
        placeholder="Your username"
        @keyup="validate"
      />
      <InputError v-if="formErrors.username">
        {{ formErrors.username }}
      </InputError>
    </div>

    <div class="mb-3.5">
      <Label>Your email</Label>
      <input
        v-model="form.email"
        :disabled="loading"
        class="w-full p-2.5 border rounded-xl border-gray-400"
        placeholder="Your email"
        type="email"
        @keyup="validate"
      />
      <InputError v-if="formErrors.email">
        {{ formErrors.email }}
      </InputError>
    </div>

    <div class="mb-3.5">
      <Label>Your password</Label>
      <input
        v-model="form.password"
        :disabled="loading"
        class="w-full p-2.5 border rounded-xl border-gray-400"
        placeholder="*************"
        type="password"
        @keyup="validate"
      />
      <InputError v-if="formErrors.password">
        {{ formErrors.password }}
      </InputError>
    </div>

    <Button
      :disabled="loading"
      type="submit"
      class="w-full border border-violet-700 text-violet-700 mb-3.5 inline-flex justify-between items-center"
    >
      <p>Register</p>
      <Spinner v-if="loading" class="!text-violet-700" />
    </Button>

    <div class="inline-flex w-full justify-end items-center">
      <router-link to="/auth/login" class="text-gray-500">Already registered?</router-link>
    </div>
  </form>
</template>

<script lang="ts">
import { $auth } from "@plurali/api-client";
import { defineComponent, reactive, ref } from "vue";
import { useRouter } from "vue-router";

import { setAuth, wrapRequest } from "../../api";
import Button from "../../components/Button.vue";
import InputError from "../../components/InputError.vue";
import Label from "../../components/Label.vue";
import Spinner from "../../components/Spinner.vue";
import Subtitle from "../../components/Subtitle.vue";
import Title from "../../components/Title.vue";
import { emailRegex } from "../../utils";

export default defineComponent({
  components: {
    Spinner,
    InputError,
    Title,
    Subtitle,
    Button,
    Label,
  },
  setup() {
    const router = useRouter();

    const form = reactive({
      username: "",
      email: "",
      password: "",
    });

    const formErrors = reactive({
      username: null as string | null,
      email: null as string | null,
      password: null as string | null,
    });

    const loading = ref(false);

    const validate = () => {
      formErrors.username =
        !form.username || form.username.trim().length < 3 ? "Username must be at least 3 characters long." : null;

      formErrors.email = !form.email || !emailRegex.test(form.email) ? "A valid email must be entered." : null;

      formErrors.password =
        !form.password || form.password.trim().length < 4 ? "Password must be at least 4 characters long." : null;

      return !formErrors.username && !formErrors.password && !formErrors.email;
    };

    const submit = async () => {
      if (loading.value) return;
      loading.value = true;

      const ok = await wrapRequest(() => $auth.register(form));
      loading.value = false;

      if (ok) {
        setAuth(ok.token);
        await router.push("/dashboard");
      }
    };

    return {
      form,
      formErrors,
      loading,
      validate,
      submit,
    };
  },
});
</script>

// apps/frontend-v2/src/pages/auth/register/index.tsx
import { minLength, required } from '@/app/utils/form';
import { Button } from '@/components/ui/elements/Button';
import { InputError } from '@/components/ui/form/InputError';
import { Label } from '@/components/ui/form/Label';
import { Subtitle } from '@/components/ui/typography/Subtitle';
import { Title } from '@/components/ui/typography/Title';
import { AlertType, useAlert, useClearAlerts } from '@/store/alert';
import { AuthRequestInterface } from '@app/v2/dto/auth/request/AuthRequestInterface';
import { $auth } from '@plurali/api-client';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useForm } from 'react-hook-form';

export const RegisterPage = () => {
  const {
    handleSubmit,
    register,
    formState: { errors },
  } = useForm<AuthRequestInterface>();
  const alert = useAlert();
  const clearAlerts = useClearAlerts();
  const [submitting] = useState(false);
  const router = useRouter();

  const onSubmit = async (data: AuthRequestInterface) => {
    clearAlerts();

    const res = await $auth.login(data);

    if (res.success) {
      router.push('/dashboard');
    } else {
      alert(res.error.message, AlertType.Danger);
    }
  };

  return (
    <>
      <div className="mb-5">
        <Title>Login</Title>
        <Subtitle>Login to your Plurali account</Subtitle>
      </div>

      <form className="mb-4 w-full" onSubmit={handleSubmit(onSubmit)}>
        <div className="mb-3.5">
          <Label>Your username</Label>

          <input
            className="w-full p-2.5 border rounded-xl border-gray-400 outline-none focus:outline-none"
            placeholder="Your username"
            {...register('username', { required, minLength: minLength(4) })}
          />

          {errors.username && <InputError>{errors.username.message}</InputError>}
        </div>

        <div className="mb-3.5">
          <Label>Your password</Label>

          <input
            className="w-full p-2.5 border rounded-xl border-gray-400 outline-none focus:outline-none"
            placeholder="*************"
            type="password"
            {...register('password', { required, minLength: minLength(4) })}
          />

          {errors.password && <InputError>{errors.password.message}</InputError>}
        </div>

        <Button
          loading={submitting}
          disabled={submitting}
          type="submit"
          className="w-full border border-violet-700 text-violet-700 mb-3.5 inline-flex justify-between items-center"
        >
          <p>Login</p>
        </Button>

        <div className="inline-flex w-full justify-end items-center">
          <Link href="/auth/register" className="text-gray-500">
            Don't have an account yet?
          </Link>
        </div>
      </form>
    </>
  );
};

export default RegisterPage;
