// packages/frontend/src/components/global/system/SystemSummary.vue
<template>
  <div
    class="mb-5 flex flex-col text-center sm:flex-row sm:text-left justify-left items-center gap-4"
  >
    <img
      v-if="currentSystem.avatar"
      :src="currentSystem.avatar"
      :alt="currentSystem.username"
      class="flex-shrink-0 w-32 h-32 rounded-full object-cover"
    />
    <Color
      v-else
      :color="currentSystem.color ?? '#e2e8f0'"
      class="flex-shrink-0 w-32 h-32 opacity-25"
    />
    <div>
      <p class="text-sm text-gray-700" v-if="isDashboard">SID: {{ currentSystem.id }}</p>
      <PageTitle class="inline-flex flex-col sm:flex-row items-center justify-center gap-3">
        {{ currentSystem.username }}
        <VisibilityTag
          v-if="isDashboard"
          :disabled="toggling"
          :visible="currentSystem.data.visible"
          @click.prevent="toggleVisibility"
        />
        <a
          v-if="isDashboard && currentSystem.data.visible"
          :href="`/${currentSystem.data.slug}`"
          class="text-sm text-gray-700 border-b border-b-gray-400 font-normal"
          target="_blank"
          rel="noopener noreferrer"
        >
          <u>Open public view</u>
        </a>
      </PageTitle>
      <Subtitle class="mb-3">{{ currentSystem.description ?? 'No description' }}</Subtitle>
      <span v-if="currentSystem.color" class="inline-flex text-gray-700 items-center gap-1">
        Color: {{ currentSystem.color }}
        <ColorCircle :color="currentSystem.color" />
      </span>
    </div>
  </div>
</template>
<script lang="ts">
import PageTitle from '../../Title.vue'
import Color from '../color/ColorCircle.vue'
import Subtitle from '../../Subtitle.vue'
import ColorCircle from '../color/ColorCircle.vue'
import { computed, defineComponent, PropType, ref } from 'vue'
import { System } from '@plurali/common/src/system'
import { useRoute } from 'vue-router'
import VisibilityTag from '../visibility/VisibilityTag.vue'
import { wrapRequest } from '../../../api'
import { updateSystem } from '../../../api/system'

export default defineComponent({
  components: {
    VisibilityTag,
    PageTitle,
    Color,
    Subtitle,
    ColorCircle,
  },
  props: {
    system: {
      type: Object as PropType<System>,
      required: true,
    },
  },
  setup({ system: _system }) {
    const route = useRoute()

    const toggling = ref(false)

    const currentSystem = ref(_system)

    const toggleVisibility = async () => {
      if (toggling.value) return
      toggling.value = true

      const res = await wrapRequest(() =>
        updateSystem(currentSystem.value.id, {
          visible: !currentSystem.value.data.visible,
        })
      )

      // fail??? refresh
      if (!res) return (window.location.href = '')

      currentSystem.value = res.system
      toggling.value = false
    }

    return {
      currentSystem,
      toggleVisibility,
      toggling,
      isDashboard: computed(() => route.path.startsWith('/dashboard')),
    }
  },
})
</script>

// frontend-v2/src/components/system/SystemSummary.tsx
import { Title } from '../ui/typography/Title';
import { Subtitle } from '../ui/typography/Subtitle';
import { Sanitized } from '../Sanitized';
import { string } from '@/app/system/field/utils';
import { SystemDtoInterface } from '@app/v2/dto/system/SystemDtoInterface';
import { ColorCircle } from '../ui/elements/ColorCircle';
import { Tag } from '../ui/elements/Tag';
import { Visibility } from '@prisma/client';
import { useSystemMutation } from '@/hooks/system/mutation';
import { DocumentIcon } from '@heroicons/react/24/outline';
import { useState } from 'react';
import Link from 'next/link';
import { Editor } from '../ui/form/Editor';
import { ButtonLink } from '../ui/elements/Button';

export interface SystemSummaryProps {
  system: SystemDtoInterface;
  dashboardMode?: boolean;
}

export const SystemSummary = ({ system, dashboardMode = false }: SystemSummaryProps) => {
  const mutation = useSystemMutation();

  const [disabled, setDisabled] = useState(false);

  const toggleVisibility = async () => {
    setDisabled(true);

    try {
      await mutation.mutateAsync({
        visibility: system.data.visibility === Visibility.Public ? Visibility.Private : Visibility.Public,
      });
    } catch (e) {
      console.error('Failed to toggle visibility for system', { system, e });
    }

    setDisabled(false);
  };

  return (
    <>
      <div className="flex justify-between items-start">
        <div className="mb-5 flex flex-col text-center sm:flex-row sm:text-left justify-left items-center gap-4">
          {system.avatar ? (
            <img src={system.avatar} alt={system.name} className="flex-shrink-0 w-32 h-32 rounded-full object-cover" />
          ) : (
            <ColorCircle color={system.color} className="flex-shrink-0 !w-32 !h-32 opacity-25" />
          )}

          <div>
            {dashboardMode && <p className="text-sm text-gray-700">ID: {system.id}</p>}

            <Title className="inline-flex flex-col sm:flex-row items-center justify-center gap-3">
              {system.name}

              {dashboardMode && (
                <>
                  <Tag
                    toggled={system.data.visibility === Visibility.Public}
                    disabled={disabled}
                    onToggle={toggleVisibility}
                  >
                    {system.data.visibility}
                  </Tag>

                  {system.data.visibility === Visibility.Public && (
                    <Link
                      href={`/${system.data.slug}`}
                      className="text-sm text-gray-700 font-normal"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      <u>Open public view</u>
                    </Link>
                  )}
                </>
              )}
            </Title>

            {system.description && (
              <Subtitle className="mb-3">
                <Sanitized unsafeValue={string(system.description, true)} />
              </Subtitle>
            )}

            {system.color && (
              <span className="inline-flex text-gray-700 items-center gap-1">
                Color: {system.color} <ColorCircle color={system.color} />
              </span>
            )}
          </div>
        </div>

        {dashboardMode && (
          <div className="flex items-center gap-2">
            <ButtonLink
              href={'/dashboard/system/page/add'}
              className="border-[2.5px] bg-white bg-opacity-25 border-violet-300 text-black inline-flex justify-center items-center gap-1"
            >
              <DocumentIcon className="w-8 h-8 -ml-1" />
              <span>New Page</span>
            </ButtonLink>
          </div>
        )}
      </div>

      {dashboardMode ? (
        <Editor
          initialValue={system.data.description ?? ''}
          placeholder={`Add custom description for ${system.name}...`}
        />
      ) : (
        <></>
      )}
    </>
  );
};
