// frontend-v2/src/components/Sanitized.tsx
import { Sanitizer } from '@/app/sanitizer';
import { setHTML } from '@/app/sanitizer/polyfill';
import { hasWindow } from '@/app/utils';
import { useState, useEffect } from 'react';

export interface SanitizedProps {
  unsafeValue: string;
}

export const Sanitized = ({ unsafeValue }: SanitizedProps) => {
  const [ref, setRef] = useState<HTMLDivElement | null>(null);

  useEffect(() => {
    if (hasWindow() && ref) {
      const sanitizer = new Sanitizer();
      setHTML.bind(ref)(unsafeValue, { sanitizer });
    }
  }, [ref, unsafeValue]);

  return <div ref={setRef}></div>;
};

// packages/frontend/src/components/global/Sanitized.vue
<template>
  <div ref="div"></div>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from 'vue';
import { Sanitizer } from '../../sanitizer';
import { setHTML } from '../../sanitizer/polyfill';

export default defineComponent({
  props: {
    value: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const s = ref<Sanitizer>(new Sanitizer());
    const div = ref<HTMLDivElement>();

    onMounted(() => {
      if (div.value) {
        setHTML.bind(div.value)(props.value, { sanitizer: s.value });
      }
    });

    return {
      s,
      div,
    };
  },
});
</script>
