// apps/frontend-v2/src/components/ui/form/Uploader.tsx
import { c } from '@/app/utils';
import { ModelProps, WithClassName } from '@/components/types/utils';
import { DocumentArrowUpIcon } from '@heroicons/react/24/outline';
import { ChangeEventHandler, DragEventHandler, useEffect, useMemo, useState } from 'react';

export interface UploaderProps extends WithClassName, ModelProps<Blob | null> {
  accept?: string[];
}

export const Uploader = ({
  value,
  setValue,
  accept = ['image/png', 'image/jpeg', 'image/avif', 'image/gif', 'image/webp'],
  className,
}: UploaderProps) => {
  const dragEvents: string[] = ['dragenter', 'dragleave', 'dragover', 'drop'];

  const [dragged, setDragged] = useState(false);
  const [input, setInput] = useState<HTMLInputElement | null>(null);

  const thumbnail = useMemo(() => (value ? URL.createObjectURL(value) : null), [value]);

  const handleDrop: DragEventHandler<HTMLDivElement> = e => {
    e.preventDefault();

    setDragged(false);

    if (e.dataTransfer?.files && e.dataTransfer.files.length >= 1) {
      const file = e.dataTransfer.files.item(0);
      setValue(file);
    }
  };

  const handleChange: ChangeEventHandler<HTMLInputElement> = e => {
    e.preventDefault();

    if (input?.files) {
      setValue(input.files.length >= 1 ? input.files.item(0) : null);
    }
  };

  useEffect(() => {
    const prevent = (e: Event) => e.preventDefault();

    dragEvents.forEach(eventName => document.body.addEventListener(eventName, prevent));

    return () => {
      dragEvents.forEach(e => document.body.removeEventListener(e, prevent));
    };
  }, []);

  return (
    <div
      onDragOver={() => setDragged(true)}
      onDragLeave={() => setDragged(false)}
      onDrop={handleDrop}
      onClick={() => input?.click()}
      className={c(
        'w-full min-h-[10rem] h-full inset-0 flex justify-center items-center rounded-2xl cursor-pointer',
        !value && 'bg-gray-100 bg-opacity-50',
        className,
      )}
    >
      <input ref={setInput} type="file" className="hidden" accept={accept.join(',')} onChange={handleChange} />
      {!dragged && !thumbnail ? (
        <div className="inline-flex justify-center items-center gap-4">
          <div className="inline-flex h-16 w-16 items-center justify-center rounded-full bg-violet-100 shadow-xl">
            <DocumentArrowUpIcon className="h-8 w-8 text-violet-600" aria-hidden="true" />
          </div>
          <p className="text-2xl text-violet-600 font-light hidden uppercase md:inline-block t">
            {value && !thumbnail ? 'Preview not available' : 'or drag & drop'}
          </p>
        </div>
      ) : dragged ? (
        <div className="text-2xl text-violet-600 font-medium hidden md:inline-block">you're almost there!</div>
      ) : (
        thumbnail && (
          <img
            src="thumbnail"
            className="rounded-2xl sm:max-h-64 md:max-h-[32rem] border-2 border-violet-500 border-opacity-50"
          />
        )
      )}
    </div>
  );
};

// packages/frontend/src/components/global/Uploader.vue
<template>
  <div
    @dragover="() => (dragged = true)"
    @dragleave="() => (dragged = false)"
    @drop.prevent="onDrop"
    class="w-full min-h-[10rem] h-full inset-0 flex justify-center items-center rounded-2xl cursor-pointer"
    @click="() => uploaderEl?.click()"
    :class="!upload && 'bg-gray-100 bg-opacity-50'"
  >
    <input type="file" ref="uploaderEl" class="hidden" :accept="accept.join(',')" @change="onChange" />
    <div v-if="!dragged && !thumbnail" class="inline-flex justify-center items-center gap-4">
      <div class="inline-flex h-16 w-16 items-center justify-center rounded-full bg-violet-100 shadow-xl">
        <DocumentArrowUpIcon class="h-8 w-8 text-violet-600" aria-hidden="true" />
      </div>
      <p class="text-2xl text-violet-600 font-light hidden uppercase md:inline-block t">
        {{ upload && !thumbnail ? 'Preview not available' : 'or drag & drop' }}
      </p>
    </div>

    <div v-else-if="dragged" class="text-2xl text-violet-600 font-medium hidden md:inline-block">
      you're almost there!
    </div>

    <img
      v-else-if="thumbnail"
      :src="thumbnail"
      class="rounded-2xl sm:max-h-64 md:max-h-[32rem] border-2 border-violet-500 border-opacity-50"
    />
  </div>
</template>

<script lang="ts">
import { DocumentArrowUpIcon } from '@heroicons/vue/24/outline';
import { PropType, computed, defineComponent, onMounted, onUnmounted, ref } from 'vue';

export default defineComponent({
  props: {
    modelValue: {
      type: Object as PropType<Blob | null>,
      default: null,
    },
    accept: {
      type: Array as PropType<string[]>,
      default: ['image/png', 'image/jpeg', 'image/avif', 'image/gif', 'image/webp'],
    },
  },
  emits: ['update:modelValue', 'submit'],
  setup(props, { emit }) {
    const dragged = ref(false);

    const uploaderEl = ref<HTMLInputElement | null>(null);

    const upload = computed({
      get() {
        return props.modelValue;
      },
      set(v) {
        emit('update:modelValue', v);
      },
    });

    const thumbnail = computed(() => {
      if (!upload.value) return null;
      try {
        return URL.createObjectURL(upload.value);
      } catch {
        return null;
      }
    });

    const onChange = () => {
      if (uploaderEl.value && uploaderEl.value.files) {
        upload.value = uploaderEl.value.files.length >= 1 ? uploaderEl.value.files.item(0) : null;
      }
    };

    const onDrop = (e: DragEvent) => {
      dragged.value = false;
      if (e.dataTransfer?.files && e.dataTransfer.files.length >= 1) {
        const file = e.dataTransfer.files.item(0);
        // if (file?.type && props.accept.find(accepted => file.type.toLowerCase() === accepted.toLowerCase())) {
          upload.value = file;
        // }
      }
    };

    const _prevent = (e: Event) => e.preventDefault();

    const dragEvents: string[] = ['dragenter', 'dragleave', 'dragover', 'drop'];

    onMounted(() => dragEvents.forEach(eventName => document.body.addEventListener(eventName, _prevent)));
    onUnmounted(() => dragEvents.forEach(e => document.body.removeEventListener(e, _prevent)));

    return {
      dragged,
      uploaderEl,
      onChange,
      onDrop,
      upload,
      thumbnail,
    };
  },
  components: { DocumentArrowUpIcon },
});
</script>
